name: node ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm build
      run:
        npm ci
        npm run build --if-present
    - name: Running unit tests
      run: npm test
      env:
        CI: true
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./coverage
        fail_ci_if_error: true
        verbose: true
